# Generated by Django 5.0 on 2024-01-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='file',
            field=models.FileField(default='documents/default.pdf', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
