# Generated by Django 5.0.1 on 2024-01-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0002_remove_pdfdocument_pdf_file_pdfdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='user_provided_name',
            field=models.CharField(default='No_Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
